### ISSUE TITLE
ASAN stack-use-after-scope at Kernel/Term.hpp:98

### ISSUE THREAD

**Issue by rainoftime** [vprover/vampire#107]
Hi, for the following formula
~~~~
(set-logic LRA)
(assert (distinct (distinct true true true true true true true (< 4229.0 0.0 1067292.0 0.0)) true true true true true true))
(check-sat)
~~~~
ASAN detects a stack-use-after-scope issue in vampire_dbg_z3 (commit 2a17f463297e)
I use z3 4.8.5 for building vampire.
~~~~
==56229==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffeef04a7a0 at pc 0x000000537d71 bp 0x7ffeef04a2a0 sp 0x7ffeef04a290
READ of size 8 at 0x7ffeef04a7a0 thread T0
    #0 0x537d70 in Kernel::TermList::tag() const Kernel/Term.hpp:98
    #1 0x56000d in Kernel::TermList::isEmpty() const Kernel/Term.hpp:101
    #2 0x746f03 in Kernel::TermTransformer::transform(Kernel::Term*) Kernel/TermTransformer.cpp:59
    #3 0x7480ca in Kernel::TermTransformer::transform(Kernel::Literal*) Kernel/TermTransformer.cpp:149
    #4 0xbba5fb in Shell::InterpretedNormalizer::NLiteralTransformer::apply(Kernel::Literal*, bool&, Kernel::Literal*&, bool&) Shell/Interprete
dNormalizer.cpp:273
    #5 0xbbbb2e in Shell::InterpretedNormalizer::NFormulaTransformer::applyLiteral(Kernel::Formula*) Shell/InterpretedNormalizer.cpp:427
    #6 0x5834ac in Kernel::FormulaTransformer::apply(Kernel::Formula*) Kernel/FormulaTransformer.cpp:59
    #7 0x584a16 in Kernel::FormulaTransformer::applyJunction(Kernel::Formula*) Kernel/FormulaTransformer.cpp:168
    #8 0x58a380 in Kernel::FormulaTransformer::applyAnd(Kernel::Formula*) Kernel/FormulaTransformer.hpp:65
    #9 0x58354a in Kernel::FormulaTransformer::apply(Kernel::Formula*) Kernel/FormulaTransformer.cpp:62
    #10 0x58323a in Kernel::FormulaTransformer::transform(Kernel::Formula*) Kernel/FormulaTransformer.cpp:42
    #11 0xbbebfd in Kernel::FTFormulaUnitTransformer<Shell::InterpretedNormalizer::NFormulaTransformer>::transform(Kernel::Formula*) Kernel/For
mulaTransformer.hpp:176
    #12 0x5869e0 in Kernel::LocalFormulaUnitTransformer::transform(Kernel::FormulaUnit*) Kernel/FormulaTransformer.cpp:367
    #13 0xbb5f20 in Shell::InterpretedNormalizer::apply(Lib::List<Kernel::Unit*>*&) Shell/InterpretedNormalizer.cpp:498
    #14 0xbb5c0d in Shell::InterpretedNormalizer::apply(Kernel::Problem&) Shell/InterpretedNormalizer.cpp:462
    #15 0xdf31c0 in Shell::Preprocess::preprocess(Kernel::Problem&) Shell/Preprocess.cpp:205
    #16 0x13d0286 in getPreprocessedProblem() /home/rainoftime/Work/tofuzz/vampire/vampire.cpp:169
    #17 0x13d0798 in doProving() /home/rainoftime/Work/tofuzz/vampire/vampire.cpp:209
    #18 0x13d4756 in vampireMode() /home/rainoftime/Work/tofuzz/vampire/vampire.cpp:607
    #19 0x13d72f1 in main /home/rainoftime/Work/tofuzz/vampire/vampire.cpp:889
    #20 0x7f96299c782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
~~~~

**Comment by rainoftime** [comment]
Here is another instance
~~~~
(set-logic LIA)
(assert (distinct true true (distinct true true) true true true true (>= 99 0) true true))
(check-sat)
~~~~

**Comment by quickbeam123** [comment]
Thank you, Jack, for the report. The most recent version of master should now be fixed.
