### ISSUE TITLE
Latex output leads to aborted signal SIGSEGV

### ISSUE THREAD

**Issue by bit-space-42** [vprover/vampire#129]
If I run the following:
`vampire --latex_output proof.tex test.p`

Where `test.p` is simply:
```
fof(tree_B, hypothesis, ? [P0, G1, C2, L3] :
( p1(P0,play01)
  & ( p21(P0,G1) )
  & ( p20(P0,C2) )
  & ( p23(P0,L3) ) ) ).

fof(tree_B, conjecture, ? [P0, G1, C2, L3] :
( p1(P0,play01)
  & ( p21(P0,G1) )
  & ( p20(P0,C2) )
  & ( p23(P0,L3) ) ) ).
```

I get the following output:
```
...
% SZS output end Proof for test
39779 Aborted by signal SIGSEGV on test.p
% ------------------------------
% Version: Vampire 4.4.0 (commit 51cbd2f on 2019-08-29 00:55:07 +0200)
% Termination reason: Refutation

% Memory used [KB]: 4861
% Time elapsed: 0.0000 s
% ------------------------------
% ------------------------------
```
and proof.tex is empty.

Interestingly enough, if I use this TPTP file instead (changing `L3` to `C2` in the last line of each fof in the previous TPTP file):
```
fof(tree_B, hypothesis, ? [P0, G1, C2, L3] :
( p1(P0,play01)
  & ( p21(P0,G1) )
  & ( p20(P0,C2) )
  & ( p23(P0,C2) ) ) ).

fof(tree_B, conjecture, ? [P0, G1, C2, L3] :
( p1(P0,play01)
  & ( p21(P0,G1) )
  & ( p20(P0,C2) )
  & ( p23(P0,C2) ) ) ).
```
it is successful in outputting a Latex file.

**Comment by selig** [comment]
Hi, LaTeX output was never updated to handle AVATAR properly after we updated how those proofs are represented... I suspect the successful output file doesn't make sense as a proof. I'm fixing it now (today/tomorrow).

**Comment by selig** [comment]
I've just pushed a fix to the master branch. I made the decision to treat AVATAR in the same way as we do in TPTP proof output. Let me know if you notice anything strange or if you have any associated feature requests. 

There is an undocumented feature that allows you to specify custom formats for predicates and functions (e.g. infix output) in LaTeX, which can make proofs much nicer. Let me know if you want an example of this.

**Comment by bit-space-42** [comment]
Thank you for the fantastically quick turnaround! I cloned the latest master from the repository, built it using `make vampire` and tried to run the following:

`./vampire --time_limit 5s --latex_output proof.tex test.p`

With `test.p` (same as above) given by:
```
fof(tree_B, hypothesis, ? [P0, G1, C2, L3] :
( p1(P0,play01)
  & ( p21(P0,G1) )
  & ( p20(P0,C2) )
  & ( p23(P0,L3) ) ) ).

fof(tree_B, conjecture, ? [P0, G1, C2, L3] :
( p1(P0,play01)
  & ( p21(P0,G1) )
  & ( p20(P0,C2) )
  & ( p23(P0,L3) ) ) ).
```
Unfortunately, this still leads to an exception, with the following output:
```
% Refutation found. Thanks to Tanya!
% SZS status Theorem for test
% SZS output start Proof for test
1. ? [X0,X1,X2,X3] : (p23(X0,X3) & p20(X0,X2) & p21(X0,X1) & p1(X0,play01)) [input]
2. ? [X0,X1,X2,X3] : (p23(X0,X3) & p20(X0,X2) & p21(X0,X1) & p1(X0,play01)) [input]
3. ~? [X0,X1,X2,X3] : (p23(X0,X3) & p20(X0,X2) & p21(X0,X1) & p1(X0,play01)) [negated conjecture 2]
4. ! [X0,X1,X2,X3] : (~p23(X0,X3) | ~p20(X0,X2) | ~p21(X0,X1) | ~p1(X0,play01)) [ennf transformation 3]
5. ? [X0,X1,X2,X3] : (p23(X0,X3) & p20(X0,X2) & p21(X0,X1) & p1(X0,play01)) => (p23(sK0,sK3) & p20(sK0,sK2) & p21(sK0,sK1) & p1(sK0,play01)) [choice axiom]
6. p23(sK0,sK3) & p20(sK0,sK2) & p21(sK0,sK1) & p1(sK0,play01) [skolemisation 1,5]
7. p1(sK0,play01) [cnf transformation 6]
8. p21(sK0,sK1) [cnf transformation 6]
9. p20(sK0,sK2) [cnf transformation 6]
10. p23(sK0,sK3) [cnf transformation 6]
11. ~p23(X0,X3) | ~p20(X0,X2) | ~p21(X0,X1) | ~p1(X0,play01) [cnf transformation 4]
12. ~p20(sK0,X0) | ~p21(sK0,X1) | ~p1(sK0,play01) [resolution 11,10]
13. ~p20(sK0,X0) | ~p21(sK0,X1) [subsumption resolution 12,7]
15. 1 <=> ! [X1] : ~p21(sK0,X1) [avatar definition]
16. ~p21(sK0,X1) <- (1) [avatar component clause 15]
18. 2 <=> ! [X0] : ~p20(sK0,X0) [avatar definition]
19. ~p20(sK0,X0) <- (2) [avatar component clause 18]
20. 1 | 2 [avatar split clause 13,18,15]
21. $false <- (2) [resolution 19,9]
22. ~2 [avatar contradiction clause 21]
23. $false <- (1) [resolution 16,8]
24. ~1 [avatar contradiction clause 23]
25. $false [avatar sat refutation 20,22,24]
% SZS output end Proof for test
=================================================================
==46342==ERROR: AddressSanitizer: global-buffer-overflow on address 0x564ef48a8748 at pc 0x564ef2ec5a15 bp 0x7ffeb56f83f0 sp 0x7ffeb56f83e0
READ of size 8 at 0x564ef48a8748 thread T0
    #0 0x564ef2ec5a14 in std::__cxx11::basic_string<char, std::char_traits<char>, Lib::STLAllocator<char> >::length() const /usr/include/c++/10.1.0/bits/basic_string.h:908
    #1 0x564ef2ed9d32 in std::__cxx11::basic_string<char, std::char_traits<char>, Lib::STLAllocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, Lib::STLAllocator<char> > const&) /usr/include/c++/10.1.0/bits/basic_string.h:451
    #2 0x564ef3704245 in Shell::LaTeX::toString[abi:cxx11](Kernel::Formula*) const Shell/LaTeX.cpp:228
    #3 0x564ef3706460 in Shell::LaTeX::toString[abi:cxx11](Kernel::Formula*, Kernel::Connective) const Shell/LaTeX.cpp:299
    #4 0x564ef37044cb in Shell::LaTeX::toString[abi:cxx11](Kernel::Formula*) const Shell/LaTeX.cpp:238
    #5 0x564ef370371c in Shell::LaTeX::toString[abi:cxx11](Kernel::Unit*) Shell/LaTeX.cpp:197
    #6 0x564ef370c397 in Shell::LaTeX::toStringAsInference[abi:cxx11](Kernel::Unit*) Shell/LaTeX.cpp:669
    #7 0x564ef37029b2 in Shell::LaTeX::refutationToString[abi:cxx11](Kernel::Unit*) Shell/LaTeX.cpp:148
    #8 0x564ef3a1f3b1 in Shell::UIHelper::outputResult(std::ostream&) Shell/UIHelper.cpp:449
    #9 0x564ef3f0b7e9 in vampireMode() ~/github/vampire/vampire.cpp:616
    #10 0x564ef3f0e4dd in main ~/github/vampire/vampire.cpp:900
    #11 0x7f1c7de61001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #12 0x564ef2e74dbd in _start (~/github/vampire/vampire+0x2eedbd)

0x564ef48a8748 is located 56 bytes to the left of global variable '__ioinit' defined in '/usr/include/c++/10.1.0/iostream:74:25' (0x564ef48a8780) of size 1
  '__ioinit' is ascii string ''
0x564ef48a8748 is located 0 bytes to the right of global variable 'guard variable for Shell::LaTeX::toString[abi:cxx11](Kernel::Formula*) const::names' defined in 'Shell/LaTeX.cpp:223:18' (0x564ef48a8740) of size 8
SUMMARY: AddressSanitizer: global-buffer-overflow /usr/include/c++/10.1.0/bits/basic_string.h:908 in std::__cxx11::basic_string<char, std::char_traits<char>, Lib::STLAllocator<char> >::length() const
Shadow bytes around the buggy address:
  0x0aca5e90d090: 01 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9
  0x0aca5e90d0a0: 00 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aca5e90d0b0: 01 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aca5e90d0c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aca5e90d0d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0aca5e90d0e0: 00 00 00 00 f9 f9 f9 f9 00[f9]f9 f9 f9 f9 f9 f9
  0x0aca5e90d0f0: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aca5e90d100: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aca5e90d110: 00 00 00 00 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x0aca5e90d120: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aca5e90d130: 00 00 00 00 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==46342==ABORTING
```
Not sure if I'm doing something wrong?

**Comment by selig** [comment]
Thanks! I forgot to add some empty strings to an array, which led Vampire to read out of bounds. Should be fixed now....

**Comment by bit-space-42** [comment]
Pulled and built the latest version, it works now, thank you!
