### ISSUE TITLE
Nondeterministic SEGV at Lib/IntUnionFind.cpp:101 (fmb)

### ISSUE THREAD

**Issue by rainoftime** [vprover/vampire#133]
[101.txt](https://github.com/vprover/vampire/files/5010393/101.txt)

vampire 61a2a24
~~~~
ASAN:SIGSEGV
=================================================================
==95300==ERROR: AddressSanitizer: SEGV on unknown address 0x7f3f99587a10 (pc 0x000000606d18 bp 0x7ffec8ad06a0 sp 0x7ffec8ad05c0 T0)
    #0 0x606d17 in Lib::IntUnionFind::root(int) const Lib/IntUnionFind.cpp:101
    #1 0x17539ae in FMB::SortInference::doInference() FMB/SortInference.cpp:356
    #2 0x17c202f in FMB::FiniteModelBuilder::init() FMB/FiniteModelBuilder.cpp:605
    #3 0x828c3f in Kernel::MainLoop::run() Kernel/MainLoop.cpp:76
    #4 0xfb627c in Saturation::ProvingHelper::runVampireSaturationImpl(Kernel::Problem&, Shell::Options const&) Saturation/ProvingHelper.cpp:152
    #5 0xfb4f64 in Saturation::ProvingHelper::runVampireSaturation(Kernel::Problem&, Shell::Options const&) Saturation/ProvingHelper.cpp:63
    #6 0x1b6239f in doProving() /home/peisen/test/tofuzz/vampire/vampire.cpp:217
    #7 0x1b6836f in vampireMode() /home/peisen/test/tofuzz/vampire/vampire.cpp:613
    #8 0x1b6ba14 in main /home/peisen/test/tofuzz/vampire/vampire.cpp:900
    #9 0x7f3e5936982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x414138 in _start (/home/peisen/test/tofuzz/vampire/vampire_z3_dbg+0x414138)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV Lib/IntUnionFind.cpp:101 Lib::IntUnionFind::root(int) const
==95300==ABORTING
~~~~

**Comment by quickbeam123** [comment]
This is now a memout. 

(Besides the problem is easy to refute by saturation.)
